name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_child_workflow_job:
    runs-on: self-hosted

    steps:
      - name: Trigger Child Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
          event-type: run-child-workflow
